# Generated by Django 2.0.3 on 2020-06-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinnerplattername',
            name='image',
            field=models.ImageField(default='no_photo.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='image',
            field=models.ImageField(default='no_photo.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='pizzaname',
            name='image',
            field=models.ImageField(default='no_photo.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='salad',
            name='image',
            field=models.ImageField(default='no_photo.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='sub',
            name='image',
            field=models.ImageField(default='no_photo.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='subname',
            name='image',
            field=models.ImageField(default='no_photo.png', upload_to=''),
        ),
    ]
